# Generated by Django 2.2.10 on 2021-03-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentdata',
            fields=[
                ('enrollment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=10)),
                ('mobile_number', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=100)),
                ('login_password', models.CharField(max_length=100)),
                ('login_otp', models.IntegerField()),
            ],
        ),
    ]
